### ISSUE TITLE
Add support for bazel BUILD

### ISSUE THREAD

**Issue by paradoxengine** [google/uuid#30]
Hello,
 I've just added a dependency to this project in a bazel compiled system and it was a bit clunky with no BUILD file around.
 My current dependency looks like this:
new_git_repository(
    name = "google_uuid",
    build_file_content = """
load("@io_bazel_rules_go//go:def.bzl", "go_prefix")
load("@io_bazel_rules_go//go:def.bzl", "go_library")
go_prefix("github.com/google/uuid")
go_library(
    name = "go_default_library",
    srcs = glob(["*.go"], exclude=["*_test.go"]),
    deps = [
    ],
    visibility = ["//visibility:public"],
)
    """,
    tag = "0.2",
    remote = "https://github.com/google/uuid",
)

It would be fairly simple to add a BUILD file - if you are ok with that I can just send a pull request (and simplify my dependencies ;-) ).

**Comment by fedir** [comment]
IMHO, it's too specific, and should not be included in this package. Probably, You could just publish a gist for those, who could need it.

**Comment by paradoxengine** [comment]
I can certainly add what I have above in a Gist, but it will remain clunky for folks using it.
I don't feel strongly about this to be honest, just figured it would be convenient and Googly. I'm ok with a project admin making the call and closing the request :)

**Comment by pborman** [comment]
Well, at a minimum it would need to be a BUILD.bazel file as BUILD is what is used by "blaze", Google's internal build system (bazel is the public version of blaze).

I am not inclined to add a BUILD.bazel, or Makefile, or CMakefile, or ANT file, or ...

You see my dilemma :-)

**Comment by paradoxengine** [comment]
Fair, I agree with your point.
