### ISSUE TITLE
Are there any plans for v1?

### ISSUE THREAD

**Issue by rocketbitz** [google/uuid#33]
Seems like the repo hasn't been tended to in a while - are there any plans to make a v1 release as mentioned in the readme?

**Comment by pborman** [comment]
Yes, it is now version 1.  I tagged it 1.0.0 but I guess I need to put the v in front, which I will do now.

**Comment by djui** [comment]
100 1.0.0 💯 ![259475a9-1a16-4317-96e7-72c827cf7083](https://user-images.githubusercontent.com/99752/44750230-17fe3a00-ab15-11e8-8d5c-e445d8fd3246.jpeg)

**Comment by rocketbitz** [comment]
👏
