### ISSUE TITLE
The v1.0.0 release has old source in zip and tar.gz files.

### ISSUE THREAD

**Issue by allenpetersen** [google/uuid#39]
I found this by using Go 1.11 modules. It would download the v1.0.0 zip file but the file contents are quite old. The copyright on each file is from 2016 and the `MustParse` function is missing.

I manually download the zip and tar.gz files and they also contain the old source.

https://github.com/google/uuid/archive/v1.0.0.zip
https://github.com/google/uuid/archive/v1.0.0.tar.gz

I had to switch my go modules to use master to work around this issue.

**Comment by allenpetersen** [comment]
@pborman could you re-release v1.0.0 to fix these bad source archives?

**Comment by pborman** [comment]
Sorry for the delay.  I have released v1.1.0 which include MustParse as well as a few other enhancements.  Please let me know if you have any problems with this release.

**Comment by allenpetersen** [comment]
@pborman This works now, thanks!
