### ISSUE TITLE
Allow concurrent, re-creatable usage

### ISSUE THREAD

**Issue by trabetti** [google/uuid#43]
Hi, I am using this package to generate uuids for a test generator. I have a use case where multiple instances of the generator run asynchronously to create tests. 
I need to be able to recreate failed tests, the current implementation holds only one seed, so there is no way to ensure recreation when processes are running asynchronously.
I have forked the repository and added a `UuidSource`, similar to a source in math/rand, which holds the `rander`, this solves my use case.
 I suggest to do a PR from my fork.

**Comment by pborman** [comment]
Sure, send me what you have.

**Comment by ahobson** [comment]
Any chance of a making a release with these changes?

**Comment by pborman** [comment]
Oh, sorry!  I will make release 1.2 now.

**Comment by pborman** [comment]
Released as 1.1.2 (changes are too minor to be a 1.2 release).  Thank you for pointing this out.
