### ISSUE TITLE
UUID to []byte?

### ISSUE THREAD

**Issue by mudream4869** [google/uuid#50]
Is there any function to get []byte from a UUID instance, or I should write the code as below?
```golang
func getBytes(u uuid.UUID) []byte {
	b := make([]byte, 16)
	for i := range b {
		b[i] = u[i]
	}
	return b
}
```

**Comment by inliquid** [comment]
`b := uuidInstance[:]`

**Comment by ferhatelmas** [comment]
also, might see [MarshalBinary](https://github.com/google/uuid/blob/master/marshal.go#L27)
